seed: 42
device: auto
data:
  root: ./toy_data
  height: 1024
  width: 128
  num_classes:
    det: 2
    type: 6
    area: 4
model:
  d_model: 512
  n_heads: 4
  ffn: 256
  dropout: 0.1
  dsa_topk: 32
train:
  batch_size: 16
  epochs: 200
  lr: 0.003
  weight_decay: 0.01
  scheduler: ReduceLROnPlateau
  loss_weights:
    det: 1.0
    type: 1.2
    snr: 0.7
    area: 1.0
    bwd: 0.5
export:
  onnx_path: ./artifacts/litejam.onnx
  dynamic_axes: true
benchmark:
  warmup: 10
  runs: 100
